name: jan_aushadhi_sarthak
description: An app to find generic medicine
publish_to: none
version: 1.0.0+1

environment:
  sdk: "^3.6.1"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.2.0
  google_mlkit_text_recognition: ^0.13.0
  http: ^1.2.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/JanAushadhi App Icon.png
